// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "esp_log.h"
#include "audio_player.h"
#include "../timer/timer.h"

#include <stdio.h>
#include <string.h>

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_MainUI;
lv_obj_t * ui_ShowInfoContainer;
lv_obj_t * ui_INFOUI;
lv_obj_t * ui_TimeUI;
lv_obj_t * ui_DateLabel;
lv_obj_t * ui_TimeLabel;
lv_obj_t * ui_WeekLabel;
lv_obj_t * ui_TempLabel;
lv_obj_t * ui_TempValueLabel;
lv_obj_t * ui_HumiLabel;
lv_obj_t * ui_HumiValueLabel;
lv_obj_t * ui_Co2Label;
lv_obj_t * ui_Co2ValueLabel;
lv_obj_t * ui_WeatherLabel;
lv_obj_t * ui_Weather;
lv_obj_t * ui_WeatherTempValLabel;
lv_obj_t * ui_DLNAUI;
lv_obj_t * ui_DLNALabel;
lv_obj_t * ui_MusicBar;
lv_obj_t * ui_MusicCurrentTime;
lv_obj_t * ui_MusicTotalTime;
lv_obj_t * ui_MusicControl1;
lv_obj_t * ui_MusicControl2;
lv_obj_t * ui_MusicControl3;
lv_obj_t * ui_ToDoListContainer;
lv_obj_t * ui_Button11;
lv_obj_t * ui_Checkbox2;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Checkbox1;
lv_obj_t * ui_TimerUI;
lv_obj_t * ui_TabView2;
lv_obj_t * ui_CountdownTabPage;
lv_obj_t * ui_HourRoller;
lv_obj_t * ui_MinRoller;
lv_obj_t * ui_SecRoller;
lv_obj_t * ui_HourLabel;
lv_obj_t * ui_MinLabel;
lv_obj_t * ui_SecLabel;
lv_obj_t * ui_CountdownBTN1;
lv_obj_t * ui_CountdownLabel1;
lv_obj_t * ui_CountdownBTN2;
lv_obj_t * ui_CountdownLabel2;
lv_obj_t * ui_TimingTabPage;
lv_obj_t * ui_OtherUI;
lv_obj_t * ui_UsageChart;
lv_chart_series_t * ui_UsageChart_series_1;
lv_chart_series_t * ui_UsageChart_series_2;
lv_obj_t * ui_CpuTempBar;
lv_obj_t * ui_NetUpLabel;
lv_obj_t * ui_NetDwLabel;
lv_obj_t * ui_CpuTitleLabel;
lv_obj_t * ui_GpuTitleLabel;
lv_obj_t * ui_RamBar;
lv_obj_t * ui_RamLabel;
lv_obj_t * ui_GRamBar;
lv_obj_t * ui_GRamLabel;
lv_obj_t * ui_GpuPowerLabel;
lv_obj_t * ui_CpuPowerLabel;
lv_obj_t * ui_CpuTempLabel;
lv_obj_t * ui_GpuTempLabel;
lv_obj_t * ui_GpuTempBar;
lv_obj_t * ui_RamUsedLabel;
lv_obj_t * ui_RamUsageLabel;
lv_obj_t * ui_GRamUsedLabel;
lv_obj_t * ui_GRamUsageLabel;
lv_obj_t * ui_DwSpeedLabel;
lv_obj_t * ui_UpSpeedLabel;
lv_obj_t * ui_NetTitleLabel;
lv_obj_t * ui_MonitorTime;
lv_obj_t * ui____initial_actions0;
lv_obj_t * ui_WeatherImage;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

#define TAG "UI"

//更改播放按钮的图标
void change_btn_icon(bool isplaying){
    if (isplaying)
    {
        lv_label_set_text(ui_MusicControl2,LV_SYMBOL_PLAY);
    }else{
        lv_label_set_text(ui_MusicControl2,LV_SYMBOL_PAUSE);
    }
}

//更改进度条的值，总时间和已播时间
void change_audio_bar(char *current_time,char *total_time,int value){
    lv_label_set_text(ui_MusicCurrentTime,current_time);
    lv_label_set_text(ui_MusicTotalTime,total_time);
    lv_slider_set_value(ui_MusicBar,value,LV_ANIM_ON);
}

//拖动进度条回调函数
void music_bar_cb(lv_obj_t *event){
    lv_obj_t* obj = lv_event_get_target(event);
    int value = lv_slider_get_value(obj);
    player_set_time(value);
    // ESP_LOGI(TAG,"slide value is %d",value);
}

//按钮回调函数
lv_res_t audio_btn_cb(lv_obj_t *event)
{
    lv_obj_t* obj = lv_event_get_target(event);

    //上一首按钮
    if (obj == ui_MusicControl1) {
        ESP_LOGI(TAG,"Previous Song");
    }
    //播放按钮
    else if (obj == ui_MusicControl2) {

        return LV_RES_OK;
    }
    //下一首按钮
    else if (obj == ui_MusicControl3) {
        ESP_LOGI(TAG,"Next Song");
    }
    return LV_RES_OK;
}

const char *Time[12+7] = {
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
    "SUN",
    "MON",
    "TUE",
    "WED",
    "THU",
    "FUI",
    "SAT",
};

//修改UI时间
void time_ui_set(int hour , int minute , int month , int monthday , int weekday){
    char dayTimeBuffer[7];
    char timeBuffer[6];
    char weekTimeBuffer[4];
    sprintf(dayTimeBuffer,"%s\n%02d",Time[month],monthday);
    sprintf(timeBuffer,"%02d:%02d",hour,minute);
    sprintf(weekTimeBuffer,"%s",Time[weekday+12]);
    lv_label_set_text(ui_DateLabel,dayTimeBuffer);
    lv_label_set_text(ui_TimeLabel,timeBuffer);
    lv_label_set_text(ui_WeekLabel,weekTimeBuffer);
    lv_label_set_text(ui_MonitorTime,timeBuffer);
    // ESP_LOGI(TAG,"%s ,%s ,%s",dayTimeBuffer,timeBuffer,weekTimeBuffer);
}

//ToDo->bugs:diskio_sdmmc: sdmmc_read_blocks failed (257)

//修改天气
void weather_ui_set(char *weather,char *code,char *temp,char *city){
    static char codeNum[4] = {0};
    char tempBuffer[6];
    static char codeBuffer[50] = {0};
    if (strcmp(code,codeNum) != 0)
    {
        sprintf(codeNum,"%s",code);
        sprintf(codeBuffer,"/sdcard/.DeskInfoScreen/weather/white/%s@1x.png",codeNum);
        lv_img_set_src(ui_WeatherImage, codeBuffer);	// 加载SD卡中的天气图片 
    }

    lv_obj_add_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    sprintf(tempBuffer,"%s°",temp);

    ESP_LOGE(TAG,"%s,%s",tempBuffer,codeBuffer);
    lv_label_set_text(ui_WeatherTempValLabel,tempBuffer);
    lv_label_set_text(ui_Weather,weather);
    lv_label_set_text(ui_WeatherLabel,city);

}

//传感器UI更新
void sensor_ui_set(float Temp,float Humi,int TVOC,int eCO2){
    char TempBuffer[10];
    char HumiBuffer[10];
    char eCO2Buffer[10];
    sprintf(TempBuffer,"%.2f°C",Temp);
    sprintf(HumiBuffer,"%.2f%%",Humi);
    sprintf(eCO2Buffer,"%d",eCO2);
    lv_label_set_text(ui_TempValueLabel, TempBuffer);
    lv_label_set_text(ui_HumiValueLabel, HumiBuffer);
    lv_label_set_text(ui_Co2ValueLabel, eCO2Buffer);
}

//0->未开启 1->开启运行中 2->开启暂停中
static int CountdownState = 0;

//倒计时UI更新
void Countdown_ui_set(int hour,int min,int sec,int endFlag){
    if (endFlag == 1)
    {
        lv_obj_set_x(ui_CountdownBTN1, 0);
        lv_label_set_text(ui_CountdownLabel1, LV_SYMBOL_PLAY);
        lv_obj_add_flag(ui_CountdownBTN2,LV_OBJ_FLAG_HIDDEN);
        CountdownState = 0;
    }else{
        lv_roller_set_selected(ui_HourRoller, hour, LV_ANIM_ON);
        lv_roller_set_selected(ui_MinRoller, min, LV_ANIM_ON);
        lv_roller_set_selected(ui_SecRoller, sec, LV_ANIM_ON);
    }
}

//倒计时按钮开始回调函数
void Countdown_btn_cb(lv_obj_t *event){
    lv_obj_t* obj = lv_event_get_target(event);
    if (obj == ui_CountdownBTN1)
    {
        if (CountdownState == 0)//未开启
        {
            uint16_t hour = lv_roller_get_selected(ui_HourRoller);
            uint16_t min = lv_roller_get_selected(ui_MinRoller);
            uint16_t sec = lv_roller_get_selected(ui_SecRoller);
            int secValue = (int)hour*3600+(int)min*60+(int)sec;
            lv_label_set_text(ui_CountdownLabel1, LV_SYMBOL_PAUSE);
            lv_obj_set_x(ui_CountdownBTN1, 80);
            lv_obj_clear_flag(ui_CountdownBTN2,LV_OBJ_FLAG_HIDDEN);
            timer_start(0,secValue);
            ESP_LOGI(TAG,"ready Countdown sec:%d",secValue);
            CountdownState = 1;
        }else if (CountdownState == 1)//开启中运行中
        {
            timer_change_state(0);
            lv_label_set_text(ui_CountdownLabel1, LV_SYMBOL_PLAY);
            CountdownState = 2;
        }else if (CountdownState == 2)//开启暂停中
        {
            timer_change_state(1);
            CountdownState = 1;
        }

    }else if (obj == ui_CountdownBTN2)//关闭定时器
    {
        if (CountdownState != 0)
        {
            timer_change_state(0);//关闭定时器
            timer_change_state(2);//杀掉任务
            Countdown_ui_set(0,10,0,0);//设置UI时间复位
            Countdown_ui_set(0,0,0,1); //设置按钮UI复位
            CountdownState = 0;
        }

        ESP_LOGI(TAG,"ui_CountdownBTN2");
    }
}


//修改性能监视器UI
void MonitorCPU_ui_set(char* title , char* power , char* usage , char* temp){
    static uint8_t init = 0;
    if(!init) {
        //对于移动处理器来说‘/’后面一般是核显名字，防止名字太长
        for (int i = 0; i < strlen(title)-1; i++)//这样直接操作cjson内的数据会导致内存泄漏吗
        {
            if (title[i] == '/')
            {
                title[i] = '\0';
                break;
            }
        }

        lv_label_set_text(ui_CpuTitleLabel,title);
        init = 1;
    }
    lv_label_set_text(ui_CpuPowerLabel,power);

    usage[strlen(usage)-1] = '\0';//去掉百分号
    lv_chart_set_next_value(ui_UsageChart, ui_UsageChart_series_1, atoi(usage));

    lv_label_set_text(ui_CpuTempLabel,temp);
    lv_bar_set_value(ui_CpuTempBar,atof(temp),LV_ANIM_ON);
}
void MonitorGPU_ui_set(char* title , char* power , char* usage , char* temp, char* usedram,char *totalram){
    static uint8_t init = 0;
    if(!init) {
        lv_label_set_text(ui_GpuTitleLabel,title);
        init = 1;
    }
    lv_label_set_text(ui_GpuPowerLabel,power);

    usage[strlen(usage)-1] = '\0';//去掉百分号
    lv_chart_set_next_value(ui_UsageChart, ui_UsageChart_series_2, atoi(usage));

    lv_label_set_text(ui_GpuTempLabel,temp);
    lv_bar_set_value(ui_GpuTempBar,atof(temp),LV_ANIM_ON);
    
    char rambuffer[20];
    char ramusagebuffer[20];
    float usedram_num = 0,totalram_num = 0;
    if (usedram[strlen(usedram)-1] == 'M')
    {
        usedram[strlen(usedram)-1] = '\0';
        usedram_num =(float)atoi(usedram)/1024.0;
    }
    else if (usedram[strlen(usedram)-1] == 'G')
    {
        usedram[strlen(usedram)-1] = '\0';
        usedram_num = atof(usedram);
    }
    
    if (totalram[strlen(totalram)-1] == 'M')
    {
        totalram[strlen(totalram)-1] = '\0';
        totalram_num = (float)atoi(totalram)/(float)1024.0;
    }
    else if (totalram[strlen(totalram)-1] == 'G')
    {
        totalram[strlen(totalram)-1] = '\0';
        totalram_num = atof(totalram);
    }
    sprintf(rambuffer,"%.1f/%.1fG",usedram_num,totalram_num);
    lv_label_set_text(ui_GRamUsedLabel,rambuffer);
    float usagep = usedram_num/totalram_num*100;
    sprintf(ramusagebuffer,"%.2f%%",usagep);
    lv_label_set_text(ui_GRamUsageLabel,ramusagebuffer);
    lv_bar_set_value(ui_GRamBar,(int)usagep,LV_ANIM_ON);
    // lv_label_set_text(ui_CpuUsageLabel,usage);
    // lv_label_set_text(ui_GRamUsedLabel,used);
}
void MonitorRAM_ui_set(char* usage , char* usedram,char *totalram){
    char rambuffer[20];
    char ramusagebuffer[20];
    float usedram_num = 0,totalram_num = 0;
    if (usedram[strlen(usedram)-1] == 'M')
    {
        usedram[strlen(usedram)-1] = '\0';
        usedram_num = atof(usedram)/1024.0;
    }
    else if (usedram[strlen(usedram)-1] == 'G')
    {
        usedram[strlen(usedram)-1] = '\0';
        usedram_num = atof(usedram);
    }
    
    if (totalram[strlen(totalram)-1] == 'M')
    {
        totalram[strlen(totalram)-1] = '\0';
        totalram_num = atof(totalram)/1024.0;
    }
    else if (totalram[strlen(totalram)-1] == 'G')
    {
        totalram[strlen(totalram)-1] = '\0';
        totalram_num = atof(totalram);
    }
    sprintf(rambuffer,"%.1f/%.1fG",usedram_num,totalram_num);
    lv_label_set_text(ui_RamUsedLabel,rambuffer);
    float usagep = usedram_num/totalram_num*100;
    sprintf(ramusagebuffer,"%.2f%%",usagep);
    lv_label_set_text(ui_RamUsageLabel,ramusagebuffer);
    lv_bar_set_value(ui_RamBar,(int)usagep,LV_ANIM_ON);
}
void MonitorNET_ui_set(char* title , char* upload , char* download){
    lv_label_set_text(ui_NetTitleLabel,title);
    lv_label_set_text(ui_UpSpeedLabel,upload);
    lv_label_set_text(ui_DwSpeedLabel,download);
}
///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);

    lv_theme_t *th = lv_theme_default_init(NULL, lv_palette_main(LV_PALETTE_DEEP_ORANGE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(NULL, th);
}
