// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "esp_log.h"
#include "audio_player.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_MainUI;
lv_obj_t * ui_ShowInfoContainer;
lv_obj_t * ui_INFOUI;
lv_obj_t * ui_TimeUI;
lv_obj_t * ui_DateLabel;
lv_obj_t * ui_TimeLabel;
lv_obj_t * ui_WeekLabel;
lv_obj_t * ui_TempLabel;
lv_obj_t * ui_TempValueLabel;
lv_obj_t * ui_HumiLabel;
lv_obj_t * ui_HumiValueLabel;
lv_obj_t * ui_Co2Label;
lv_obj_t * ui_Co2ValueLabel;
lv_obj_t * ui_WeatherLabel;
lv_obj_t * ui_Weather;
lv_obj_t * ui_WeatherTempValLabel;
lv_obj_t * ui_DLNAUI;
lv_obj_t * ui_DLNALabel;
lv_obj_t * ui_MusicBar;
lv_obj_t * ui_MusicCurrentTime;
lv_obj_t * ui_MusicTotalTime;
lv_obj_t * ui_MusicControl1;
lv_obj_t * ui_MusicControl2;
lv_obj_t * ui_MusicControl3;
lv_obj_t * ui_ToDoListContainer;
lv_obj_t * ui_Button11;
lv_obj_t * ui_Checkbox2;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Checkbox1;
lv_obj_t * ui_OtherUI;
lv_obj_t * ui____initial_actions0;
lv_obj_t * ui_WeatherImage;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

#define TAG "UI"

//更改播放按钮的图标
void change_btn_icon(bool isplaying){
    if (isplaying)
    {
        lv_label_set_text(ui_MusicControl2,LV_SYMBOL_PLAY);
    }else{
        lv_label_set_text(ui_MusicControl2,LV_SYMBOL_PAUSE);
    }
}

//更改进度条的值，总时间和已播时间
void change_audio_bar(char *current_time,char *total_time,int value){
    lv_label_set_text(ui_MusicCurrentTime,current_time);
    lv_label_set_text(ui_MusicTotalTime,total_time);
    lv_slider_set_value(ui_MusicBar,value,LV_ANIM_ON);
}

//拖动进度条回调函数
void music_bar_cb(lv_obj_t *event){
    lv_obj_t* obj = lv_event_get_target(event);
    int value = lv_slider_get_value(obj);
    player_set_time(value);
    // ESP_LOGI(TAG,"slide value is %d",value);
}

//按钮回调函数
lv_res_t audio_btn_cb(lv_obj_t *event)
{
    lv_obj_t* obj = lv_event_get_target(event);

    //上一首按钮
    if (obj == ui_MusicControl1) {
        ESP_LOGI(TAG,"Previous Song");
    }
    //播放按钮
    else if (obj == ui_MusicControl2) {

        return LV_RES_OK;
    }
    //下一首按钮
    else if (obj == ui_MusicControl3) {
        ESP_LOGI(TAG,"Next Song");
    }
    return LV_RES_OK;
}

const char *Time[12+7] = {
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
    "SUN",
    "MON",
    "TUE",
    "WED",
    "THU",
    "FUI",
    "SAT",
};

//修改UI时间
void time_ui_set(int hour , int minute , int month , int monthday , int weekday){
    char dayTimeBuffer[7];
    char timeBuffer[6];
    char weekTimeBuffer[4];
    sprintf(dayTimeBuffer,"%s\n%02d",Time[month],monthday);
    sprintf(timeBuffer,"%02d:%02d",hour,minute);
    sprintf(weekTimeBuffer,"%s",Time[weekday+12]);
    lv_label_set_text(ui_DateLabel,dayTimeBuffer);
    lv_label_set_text(ui_TimeLabel,timeBuffer);
    lv_label_set_text(ui_WeekLabel,weekTimeBuffer);
    // ESP_LOGI(TAG,"%s ,%s ,%s",dayTimeBuffer,timeBuffer,weekTimeBuffer);
}

//ToDo->bugs:diskio_sdmmc: sdmmc_read_blocks failed (257)

//修改天气
void weather_ui_set(char *weather,char *code,char *temp,char *city){
    static char codeNum[4] = {0};
    char tempBuffer[6];
    static char codeBuffer[50] = {0};
    if (strcmp(code,codeNum) != 0)
    {
        sprintf(codeNum,"%s",code);
        sprintf(codeBuffer,"/sdcard/.DeskInfoScreen/weather/white/%s@1x.png",codeNum);
        lv_img_set_src(ui_WeatherImage, codeBuffer);	// 加载SD卡中的天气图片 
    }
    
    lv_obj_add_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    sprintf(tempBuffer,"%s°",temp);
    
    ESP_LOGE(TAG,"%s,%s",tempBuffer,codeBuffer);
    lv_label_set_text(ui_WeatherTempValLabel,tempBuffer);
    lv_label_set_text(ui_Weather,weather);
    lv_label_set_text(ui_WeatherLabel,city);

}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);

    lv_theme_t *th = lv_theme_default_init(NULL, lv_palette_main(LV_PALETTE_DEEP_ORANGE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(NULL, th);
}
