// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_MainUI;
extern lv_obj_t * ui_ShowInfoContainer;
extern lv_obj_t * ui_INFOUI;
extern lv_obj_t * ui_TimeUI;
extern lv_obj_t * ui_DateLabel;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_WeekLabel;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_TempValueLabel;
extern lv_obj_t * ui_HumiLabel;
extern lv_obj_t * ui_HumiValueLabel;
extern lv_obj_t * ui_Co2Label;
extern lv_obj_t * ui_Co2ValueLabel;
extern lv_obj_t * ui_WeatherLabel;
extern lv_obj_t * ui_Weather;
extern lv_obj_t * ui_WeatherTempValLabel;

extern lv_obj_t * ui_DLNAUI;
extern lv_obj_t * ui_DLNALabel;
extern lv_obj_t * ui_MusicBar;
extern lv_obj_t * ui_MusicCurrentTime;
extern lv_obj_t * ui_MusicTotalTime;
extern lv_obj_t * ui_MusicControl1;
extern lv_obj_t * ui_MusicControl2;
extern lv_obj_t * ui_MusicControl3;
extern lv_obj_t * ui_ToDoListContainer;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Checkbox2;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Checkbox1;
extern lv_obj_t * ui_TimerUI;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_CountdownTabPage;
extern lv_obj_t * ui_HourRoller;
extern lv_obj_t * ui_MinRoller;
extern lv_obj_t * ui_SecRoller;
extern lv_obj_t * ui_HourLabel;
extern lv_obj_t * ui_MinLabel;
extern lv_obj_t * ui_SecLabel;
extern lv_obj_t * ui_CountdownBTN1;
extern lv_obj_t * ui_CountdownLabel1;
extern lv_obj_t * ui_CountdownBTN2;
extern lv_obj_t * ui_CountdownLabel2;
extern lv_obj_t * ui_TimingTabPage;
extern lv_obj_t * ui_OtherUI;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui____initial_actions0;
extern lv_obj_t * ui_WeatherImage;

void change_btn_icon(bool isplaying);
void change_audio_bar(char *current_time,char *total_time,int value);
void music_bar_cb(lv_obj_t *event);
lv_res_t audio_btn_cb(lv_obj_t *event);

void time_ui_set(int hour , int minute , int month , int monthday , int weekday);
void weather_ui_set(char *weather,char *code,char *temp,char *city);
void sensor_ui_set(float Temp,float Humi,int TVOC,int eCO2);
void Countdown_ui_set(int hour,int min,int sec,int endFlag);
void Countdown_btn_cb(lv_obj_t *event);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
