// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_MainUI;
lv_obj_t * ui_ShowInfoContainer;
lv_obj_t * ui_INFOUI;
lv_obj_t * ui_TimeUI;
lv_obj_t * ui_DateLabel;
lv_obj_t * ui_TimeLabel;
lv_obj_t * ui_WeekLabel;
lv_obj_t * ui_TempLabel;
lv_obj_t * ui_TempValueLabel;
lv_obj_t * ui_HumiLabel;
lv_obj_t * ui_HumiValueLabel;
lv_obj_t * ui_Co2Label;
lv_obj_t * ui_Co2ValueLabel;
lv_obj_t * ui_WeatherLabel;
lv_obj_t * ui_Weather;
lv_obj_t * ui_WeatherTempValLabel;
lv_obj_t * ui_Button2;
lv_obj_t * ui_DLNAUI;
lv_obj_t * ui_DLNALabel;
lv_obj_t * ui_MusicBar;
lv_obj_t * ui_MusicCurrentTime;
lv_obj_t * ui_MusicTotalTime;
lv_obj_t * ui_MusicControl1;
lv_obj_t * ui_MusicControl2;
lv_obj_t * ui_MusicControl3;
lv_obj_t * ui_ToDoListContainer;
lv_obj_t * ui_Button11;
lv_obj_t * ui_Checkbox2;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Checkbox1;
lv_obj_t * ui_OtherUI;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
