// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
//字库
#include "lv_fonts.h"

void ui_Screen1_screen_init(void)
{
    lv_port_font_harmony_sans_20_load("font_hs20");
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 0);
    lv_obj_set_width(ui_TabView1, 320);
    lv_obj_set_height(ui_TabView1, 480);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainUI = lv_tabview_add_tab(ui_TabView1, "Title 1");

    ui_ShowInfoContainer = lv_obj_create(ui_MainUI);
    lv_obj_remove_style_all(ui_ShowInfoContainer);
    lv_obj_set_width(ui_ShowInfoContainer, 320);
    lv_obj_set_height(ui_ShowInfoContainer, 180);
    lv_obj_set_x(ui_ShowInfoContainer, 0);
    lv_obj_set_y(ui_ShowInfoContainer, -145);
    lv_obj_set_align(ui_ShowInfoContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ShowInfoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_INFOUI = lv_tabview_create(ui_ShowInfoContainer, LV_DIR_TOP, 0);
    lv_obj_set_width(ui_INFOUI, 300);
    lv_obj_set_height(ui_INFOUI, 160);
    lv_obj_set_x(ui_INFOUI, 0);
    lv_obj_set_y(ui_INFOUI, -8);
    lv_obj_set_align(ui_INFOUI, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_INFOUI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_INFOUI, 20, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_TimeUI = lv_tabview_add_tab(ui_INFOUI, "Title 1");
    lv_obj_set_style_radius(ui_TimeUI, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TimeUI, lv_color_hex(0xD4ABC4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_TimeUI,LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_TimeUI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_DateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabel, 0);
    lv_obj_set_y(ui_DateLabel, 0);
    lv_obj_set_align(ui_DateLabel, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_DateLabel, "SEP\n11");
    lv_obj_set_style_text_font(ui_DateLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DateLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel, 0);
    lv_obj_set_y(ui_TimeLabel, -40);
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel, "03:42");
    lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0xF83F16), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeekLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_WeekLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeekLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeekLabel, 118);
    lv_obj_set_y(ui_WeekLabel, -28);
    lv_obj_set_align(ui_WeekLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeekLabel, "WED");
    lv_obj_set_style_text_font(ui_WeekLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WeekLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel, 55);
    lv_obj_set_y(ui_TempLabel, 5);
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel, "Temp:");
    lv_obj_set_style_text_color(ui_TempLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempValueLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_TempValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempValueLabel, 225);
    lv_obj_set_y(ui_TempValueLabel, 65);
    lv_obj_set_align(ui_TempValueLabel, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_TempValueLabel, "0°C");
    lv_obj_set_style_text_color(ui_TempValueLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumiLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_HumiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumiLabel, 55);
    lv_obj_set_y(ui_HumiLabel, 30);
    lv_obj_set_align(ui_HumiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumiLabel, "Humi:");
    lv_obj_set_style_text_color(ui_HumiLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumiValueLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_HumiValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumiValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumiValueLabel, 225);
    lv_obj_set_y(ui_HumiValueLabel, 90);
    lv_obj_set_align(ui_HumiValueLabel, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_HumiValueLabel, "0%");
    lv_obj_set_style_text_color(ui_HumiValueLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Co2Label = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_Co2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Co2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Co2Label, 55);
    lv_obj_set_y(ui_Co2Label, 55);
    lv_obj_set_align(ui_Co2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Co2Label, "Co2:");
    lv_obj_set_style_text_color(ui_Co2Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Co2ValueLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_Co2ValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Co2ValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Co2ValueLabel, 225);
    lv_obj_set_y(ui_Co2ValueLabel, 115);
    lv_obj_set_align(ui_Co2ValueLabel, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_Co2ValueLabel, "0%");
    lv_obj_set_style_text_color(ui_Co2ValueLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_WeatherLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherLabel, 0);
    lv_obj_set_y(ui_WeatherLabel, 55);
    lv_obj_set_align(ui_WeatherLabel, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_WeatherLabel, "未知");
    lv_obj_set_style_text_color(ui_WeatherLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherLabel, &font_harmony_sans_20, 0);

    ui_Weather = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_Weather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather, 95);
    lv_obj_set_y(ui_Weather, 55);
    lv_obj_set_align(ui_Weather, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_Weather, "未知");
    lv_obj_set_style_text_font(ui_Weather, &font_harmony_sans_20, 0);
    lv_obj_set_style_text_color(ui_Weather, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherImage =  lv_img_create(ui_TimeUI);
    lv_obj_set_x(ui_WeatherImage, 90);
    lv_obj_set_y(ui_WeatherImage, 85);
    lv_obj_set_align(ui_WeatherImage, LV_ALIGN_TOP_LEFT);

    ui_WeatherTempValLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_WeatherTempValLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherTempValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherTempValLabel, 0);
    lv_obj_set_y(ui_WeatherTempValLabel, 85);
    lv_obj_set_align(ui_WeatherTempValLabel, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_WeatherTempValLabel, "29°");
    lv_obj_set_style_text_color(ui_WeatherTempValLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherTempValLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DLNAUI = lv_tabview_add_tab(ui_INFOUI, "Title 2");
    lv_obj_set_style_radius(ui_DLNAUI, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DLNAUI, lv_color_hex(0x4FC597), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_DLNAUI,LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_DLNAUI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DLNALabel = lv_label_create(ui_DLNAUI);
    lv_obj_set_width(ui_DLNALabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DLNALabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DLNALabel, 0);
    lv_obj_set_y(ui_DLNALabel, -40);
    lv_obj_set_align(ui_DLNALabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DLNALabel, "DLNA");
    lv_obj_set_style_text_font(ui_DLNALabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MusicBar = lv_slider_create(ui_DLNAUI);
    lv_slider_set_value(ui_MusicBar, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_MusicBar) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_MusicBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_MusicBar, 200);
    lv_obj_set_height(ui_MusicBar, 10);
    lv_obj_set_x(ui_MusicBar, 0);
    lv_obj_set_y(ui_MusicBar, 15);
    lv_obj_set_align(ui_MusicBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_MusicBar, lv_color_hex(0x0AEFC9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_slider_set_range(ui_MusicBar, 0, 100);
    lv_obj_add_event_cb(ui_MusicBar, music_bar_cb, LV_EVENT_RELEASED , NULL);


    ui_MusicCurrentTime = lv_label_create(ui_DLNAUI);
    lv_obj_set_width(ui_MusicCurrentTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicCurrentTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MusicCurrentTime, -124);
    lv_obj_set_y(ui_MusicCurrentTime, 15);
    lv_obj_set_align(ui_MusicCurrentTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicCurrentTime, "0:00");
    lv_obj_set_style_text_color(ui_MusicCurrentTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_MusicTotalTime = lv_label_create(ui_DLNAUI);
    lv_obj_set_width(ui_MusicTotalTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicTotalTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MusicTotalTime, 124);
    lv_obj_set_y(ui_MusicTotalTime, 15);
    lv_obj_set_align(ui_MusicTotalTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicTotalTime, "0:00");
    lv_obj_set_style_text_color(ui_MusicTotalTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_MusicControl1 = lv_label_create(ui_DLNAUI);
    lv_obj_set_width(ui_MusicControl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicControl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MusicControl1, -50);
    lv_obj_set_y(ui_MusicControl1, 52);
    lv_obj_set_align(ui_MusicControl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicControl1, LV_SYMBOL_PREV);
    lv_obj_add_event_cb(ui_MusicControl1, audio_btn_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_flag(ui_MusicControl1,LV_OBJ_FLAG_CLICKABLE);

    ui_MusicControl2 = lv_label_create(ui_DLNAUI);
    lv_obj_set_width(ui_MusicControl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicControl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MusicControl2, 2);
    lv_obj_set_y(ui_MusicControl2, 52);
    lv_obj_set_align(ui_MusicControl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicControl2, LV_SYMBOL_PLAY);
    lv_obj_add_event_cb(ui_MusicControl2, audio_btn_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_flag(ui_MusicControl2,LV_OBJ_FLAG_CLICKABLE);

    ui_MusicControl3 = lv_label_create(ui_DLNAUI);
    lv_obj_set_width(ui_MusicControl3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicControl3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MusicControl3, 50);
    lv_obj_set_y(ui_MusicControl3, 52);
    lv_obj_set_align(ui_MusicControl3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicControl3, LV_SYMBOL_NEXT);
    lv_obj_add_event_cb(ui_MusicControl3, audio_btn_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_flag(ui_MusicControl3,LV_OBJ_FLAG_CLICKABLE);

    ui_ToDoListContainer = lv_obj_create(ui_MainUI);
    lv_obj_remove_style_all(ui_ToDoListContainer);
    lv_obj_set_width(ui_ToDoListContainer, 300);
    lv_obj_set_height(ui_ToDoListContainer, 291);
    lv_obj_set_x(ui_ToDoListContainer, 0);
    lv_obj_set_y(ui_ToDoListContainer, 80);
    lv_obj_set_align(ui_ToDoListContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ToDoListContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ToDoListContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ToDoListContainer, lv_color_hex(0x87C1B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_color(ui_ToDoListContainer, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ToDoListContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button11 = lv_btn_create(ui_ToDoListContainer);
    lv_obj_set_width(ui_Button11, 276);
    lv_obj_set_height(ui_Button11, 50);
    lv_obj_set_x(ui_Button11, 0);
    lv_obj_set_y(ui_Button11, -103);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Button11, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox2 = lv_checkbox_create(ui_Button11);
    lv_checkbox_set_text(ui_Checkbox2, "ToDoList_1");
    lv_obj_set_width(ui_Checkbox2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox2, -71);
    lv_obj_set_y(ui_Checkbox2, 0);
    lv_obj_set_align(ui_Checkbox2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Button1 = lv_btn_create(ui_ToDoListContainer);
    lv_obj_set_width(ui_Button1, 276);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 1);
    lv_obj_set_y(ui_Button1, -42);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Button1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox1 = lv_checkbox_create(ui_Button1);
    lv_checkbox_set_text(ui_Checkbox1, "ToDoList_2");
    lv_obj_set_width(ui_Checkbox1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox1, -71);
    lv_obj_set_y(ui_Checkbox1, 0);
    lv_obj_set_align(ui_Checkbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_OtherUI = lv_tabview_add_tab(ui_TabView1, "Title 2");


}
