// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
//字库
#include "lv_fonts.h"

void ui_Screen1_screen_init(void)
{
    lv_port_font_harmony_sans_20_load("font_hs20");
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 0);
    lv_obj_set_width(ui_TabView1, 320);
    lv_obj_set_height(ui_TabView1, 480);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainUI = lv_tabview_add_tab(ui_TabView1, "Title 1");

    ui_ShowInfoContainer = lv_obj_create(ui_MainUI);
    lv_obj_remove_style_all(ui_ShowInfoContainer);
    lv_obj_set_width(ui_ShowInfoContainer, 320);
    lv_obj_set_height(ui_ShowInfoContainer, 180);
    lv_obj_set_x(ui_ShowInfoContainer, 0);
    lv_obj_set_y(ui_ShowInfoContainer, -145);
    lv_obj_set_align(ui_ShowInfoContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ShowInfoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_INFOUI = lv_tabview_create(ui_ShowInfoContainer, LV_DIR_TOP, 0);
    lv_obj_set_width(ui_INFOUI, 300);
    lv_obj_set_height(ui_INFOUI, 160);
    lv_obj_set_x(ui_INFOUI, 0);
    lv_obj_set_y(ui_INFOUI, -8);
    lv_obj_set_align(ui_INFOUI, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_INFOUI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_INFOUI, 20, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_TimeUI = lv_tabview_add_tab(ui_INFOUI, "Title 1");
    lv_obj_set_style_radius(ui_TimeUI, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TimeUI, lv_color_hex(0xD4ABC4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_TimeUI,LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_TimeUI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_DateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabel, 0);
    lv_obj_set_y(ui_DateLabel, 0);
    lv_obj_set_align(ui_DateLabel, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_DateLabel, "SEP\n11");
    lv_obj_set_style_text_font(ui_DateLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DateLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel, 0);
    lv_obj_set_y(ui_TimeLabel, -40);
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel, "03:42");
    lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0xF83F16), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeekLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_WeekLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeekLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeekLabel, 118);
    lv_obj_set_y(ui_WeekLabel, -28);
    lv_obj_set_align(ui_WeekLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeekLabel, "WED");
    lv_obj_set_style_text_font(ui_WeekLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WeekLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel, 55);
    lv_obj_set_y(ui_TempLabel, 5);
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel, "Temp:");
    lv_obj_set_style_text_color(ui_TempLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempValueLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_TempValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempValueLabel, 225);
    lv_obj_set_y(ui_TempValueLabel, 65);
    lv_obj_set_align(ui_TempValueLabel, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_TempValueLabel, "0°C");
    lv_obj_set_style_text_color(ui_TempValueLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumiLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_HumiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumiLabel, 55);
    lv_obj_set_y(ui_HumiLabel, 30);
    lv_obj_set_align(ui_HumiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumiLabel, "Humi:");
    lv_obj_set_style_text_color(ui_HumiLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumiValueLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_HumiValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumiValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumiValueLabel, 225);
    lv_obj_set_y(ui_HumiValueLabel, 90);
    lv_obj_set_align(ui_HumiValueLabel, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_HumiValueLabel, "0%");
    lv_obj_set_style_text_color(ui_HumiValueLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Co2Label = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_Co2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Co2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Co2Label, 55);
    lv_obj_set_y(ui_Co2Label, 55);
    lv_obj_set_align(ui_Co2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Co2Label, "Co2:");
    lv_obj_set_style_text_color(ui_Co2Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Co2ValueLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_Co2ValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Co2ValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Co2ValueLabel, 225);
    lv_obj_set_y(ui_Co2ValueLabel, 115);
    lv_obj_set_align(ui_Co2ValueLabel, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_Co2ValueLabel, "0%");
    lv_obj_set_style_text_color(ui_Co2ValueLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_WeatherLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherLabel, 0);
    lv_obj_set_y(ui_WeatherLabel, 55);
    lv_obj_set_align(ui_WeatherLabel, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_WeatherLabel, "未知");
    lv_obj_set_style_text_color(ui_WeatherLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherLabel, &font_harmony_sans_20, 0);

    ui_Weather = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_Weather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather, 95);
    lv_obj_set_y(ui_Weather, 55);
    lv_obj_set_align(ui_Weather, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_Weather, "未知");
    lv_obj_set_style_text_font(ui_Weather, &font_harmony_sans_20, 0);
    lv_obj_set_style_text_color(ui_Weather, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherImage =  lv_img_create(ui_TimeUI);
    lv_obj_set_x(ui_WeatherImage, 90);
    lv_obj_set_y(ui_WeatherImage, 85);
    lv_obj_set_align(ui_WeatherImage, LV_ALIGN_TOP_LEFT);

    ui_WeatherTempValLabel = lv_label_create(ui_TimeUI);
    lv_obj_set_width(ui_WeatherTempValLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherTempValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherTempValLabel, 0);
    lv_obj_set_y(ui_WeatherTempValLabel, 85);
    lv_obj_set_align(ui_WeatherTempValLabel, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_WeatherTempValLabel, "29°");
    lv_obj_set_style_text_color(ui_WeatherTempValLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherTempValLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DLNAUI = lv_tabview_add_tab(ui_INFOUI, "Title 2");
    lv_obj_set_style_radius(ui_DLNAUI, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DLNAUI, lv_color_hex(0x4FC597), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_DLNAUI,LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_DLNAUI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DLNALabel = lv_label_create(ui_DLNAUI);
    lv_obj_set_width(ui_DLNALabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DLNALabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DLNALabel, 0);
    lv_obj_set_y(ui_DLNALabel, -40);
    lv_obj_set_align(ui_DLNALabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DLNALabel, "DLNA");
    lv_obj_set_style_text_font(ui_DLNALabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MusicBar = lv_slider_create(ui_DLNAUI);
    lv_slider_set_value(ui_MusicBar, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_MusicBar) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_MusicBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_MusicBar, 200);
    lv_obj_set_height(ui_MusicBar, 10);
    lv_obj_set_x(ui_MusicBar, 0);
    lv_obj_set_y(ui_MusicBar, 15);
    lv_obj_set_align(ui_MusicBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_MusicBar, lv_color_hex(0x0AEFC9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_slider_set_range(ui_MusicBar, 0, 100);
    lv_obj_add_event_cb(ui_MusicBar, music_bar_cb, LV_EVENT_RELEASED , NULL);


    ui_MusicCurrentTime = lv_label_create(ui_DLNAUI);
    lv_obj_set_width(ui_MusicCurrentTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicCurrentTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MusicCurrentTime, -124);
    lv_obj_set_y(ui_MusicCurrentTime, 15);
    lv_obj_set_align(ui_MusicCurrentTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicCurrentTime, "0:00");
    lv_obj_set_style_text_color(ui_MusicCurrentTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_MusicTotalTime = lv_label_create(ui_DLNAUI);
    lv_obj_set_width(ui_MusicTotalTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicTotalTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MusicTotalTime, 124);
    lv_obj_set_y(ui_MusicTotalTime, 15);
    lv_obj_set_align(ui_MusicTotalTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicTotalTime, "0:00");
    lv_obj_set_style_text_color(ui_MusicTotalTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_MusicControl1 = lv_label_create(ui_DLNAUI);
    lv_obj_set_width(ui_MusicControl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicControl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MusicControl1, -50);
    lv_obj_set_y(ui_MusicControl1, 52);
    lv_obj_set_align(ui_MusicControl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicControl1, LV_SYMBOL_PREV);
    lv_obj_add_event_cb(ui_MusicControl1, audio_btn_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_flag(ui_MusicControl1,LV_OBJ_FLAG_CLICKABLE);

    ui_MusicControl2 = lv_label_create(ui_DLNAUI);
    lv_obj_set_width(ui_MusicControl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicControl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MusicControl2, 2);
    lv_obj_set_y(ui_MusicControl2, 52);
    lv_obj_set_align(ui_MusicControl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicControl2, LV_SYMBOL_PLAY);
    lv_obj_add_event_cb(ui_MusicControl2, audio_btn_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_flag(ui_MusicControl2,LV_OBJ_FLAG_CLICKABLE);

    ui_MusicControl3 = lv_label_create(ui_DLNAUI);
    lv_obj_set_width(ui_MusicControl3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicControl3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MusicControl3, 50);
    lv_obj_set_y(ui_MusicControl3, 52);
    lv_obj_set_align(ui_MusicControl3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicControl3, LV_SYMBOL_NEXT);
    lv_obj_add_event_cb(ui_MusicControl3, audio_btn_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_flag(ui_MusicControl3,LV_OBJ_FLAG_CLICKABLE);

    ui_Todoist_list = lv_list_create(ui_MainUI);
    lv_obj_set_x(ui_Todoist_list, 0);
    lv_obj_set_y(ui_Todoist_list, 80);
    lv_obj_set_align(ui_Todoist_list, LV_ALIGN_CENTER);
    lv_obj_set_size(ui_Todoist_list, 300, 291);
    lv_obj_set_style_radius(ui_Todoist_list, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Todoist_list, lv_color_hex(0xabd4bb), LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Todoist_list, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Todoist_list, &font_harmony_sans_20, 0);
    lv_obj_set_style_border_width(ui_Todoist_list, 0, LV_PART_MAIN);
    // 调整为需要的像素间距
    lv_obj_set_style_pad_top(ui_Todoist_list, 10, LV_PART_MAIN);
    lv_obj_set_style_pad_row(ui_Todoist_list, 10, LV_PART_MAIN); 

    ui_TimerUI = lv_tabview_add_tab(ui_TabView1, "Title 2");

    ui_TabView2 = lv_tabview_create(ui_TimerUI, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView2, 320);
    lv_obj_set_height(ui_TabView2, 480);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_CountdownTabPage = lv_tabview_add_tab(ui_TabView2, "Countdown");
	lv_obj_clear_flag(ui_TimeUI,LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_scroll_dir(ui_CountdownTabPage, LV_DIR_TOP);

    ui_HourRoller = lv_roller_create(ui_CountdownTabPage);
    lv_roller_set_options(ui_HourRoller, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_HourRoller, 80);
    lv_obj_set_height(ui_HourRoller, 120);
    lv_obj_set_x(ui_HourRoller, -110);
    lv_obj_set_y(ui_HourRoller, -100);
    lv_obj_set_align(ui_HourRoller, LV_ALIGN_CENTER);

    lv_obj_set_style_text_font(ui_HourRoller, &lv_font_montserrat_20, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_MinRoller = lv_roller_create(ui_CountdownTabPage);
    lv_roller_set_options(ui_MinRoller,
                          "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_roller_set_selected(ui_MinRoller, 10, LV_ANIM_OFF);
    lv_obj_set_width(ui_MinRoller, 80);
    lv_obj_set_height(ui_MinRoller, 120);
    lv_obj_set_x(ui_MinRoller, 0);
    lv_obj_set_y(ui_MinRoller, -100);
    lv_obj_set_align(ui_MinRoller, LV_ALIGN_CENTER);

    lv_obj_set_style_text_font(ui_MinRoller, &lv_font_montserrat_20, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_SecRoller = lv_roller_create(ui_CountdownTabPage);
    lv_roller_set_options(ui_SecRoller,
                          "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_roller_set_selected(ui_SecRoller, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SecRoller, 80);
    lv_obj_set_height(ui_SecRoller, 120);
    lv_obj_set_x(ui_SecRoller, 110);
    lv_obj_set_y(ui_SecRoller, -100);
    lv_obj_set_align(ui_SecRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_SecRoller, &lv_font_montserrat_20, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_HourLabel = lv_label_create(ui_CountdownTabPage);
    lv_obj_set_width(ui_HourLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HourLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HourLabel, -110);
    lv_obj_set_y(ui_HourLabel, -180);
    lv_obj_set_align(ui_HourLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HourLabel, "Hour");

    ui_MinLabel = lv_label_create(ui_CountdownTabPage);
    lv_obj_set_width(ui_MinLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinLabel, 0);
    lv_obj_set_y(ui_MinLabel, -180);
    lv_obj_set_align(ui_MinLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinLabel, "Min");

    ui_SecLabel = lv_label_create(ui_CountdownTabPage);
    lv_obj_set_width(ui_SecLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SecLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SecLabel, 110);
    lv_obj_set_y(ui_SecLabel, -180);
    lv_obj_set_align(ui_SecLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SecLabel, "Sec");

    ui_CountdownBTN1 = lv_btn_create(ui_CountdownTabPage);
    lv_obj_set_width(ui_CountdownBTN1, 80);
    lv_obj_set_height(ui_CountdownBTN1, 50);
    lv_obj_set_x(ui_CountdownBTN1, 0);
    lv_obj_set_y(ui_CountdownBTN1, 140);
    lv_obj_set_align(ui_CountdownBTN1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_CountdownBTN1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_CountdownBTN1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_CountdownBTN1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_add_event_cb(ui_CountdownBTN1, Countdown_btn_cb, LV_EVENT_CLICKED , NULL);

    ui_CountdownLabel1 = lv_label_create(ui_CountdownBTN1);
    lv_obj_set_width(ui_CountdownLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CountdownLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CountdownLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CountdownLabel1, LV_SYMBOL_PLAY);
    lv_obj_set_style_text_font(ui_CountdownLabel1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CountdownBTN2 = lv_btn_create(ui_CountdownTabPage);
    lv_obj_set_width(ui_CountdownBTN2, 80);
    lv_obj_set_height(ui_CountdownBTN2, 50);
    lv_obj_set_x(ui_CountdownBTN2, -80);
    lv_obj_set_y(ui_CountdownBTN2, 140);
    lv_obj_set_align(ui_CountdownBTN2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_CountdownBTN2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_CountdownBTN2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_CountdownBTN2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_CountdownBTN2,LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_event_cb(ui_CountdownBTN2, Countdown_btn_cb, LV_EVENT_CLICKED , NULL);

    ui_CountdownLabel2 = lv_label_create(ui_CountdownBTN2);
    lv_obj_set_width(ui_CountdownLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CountdownLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CountdownLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CountdownLabel2, LV_SYMBOL_STOP);
    lv_obj_set_style_text_font(ui_CountdownLabel2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimingTabPage = lv_tabview_add_tab(ui_TabView2, "Timing");

    ui_OtherUI = lv_tabview_add_tab(ui_TabView1, "Title 3");




    ui_UsageChart = lv_chart_create(ui_OtherUI);
    lv_obj_set_width(ui_UsageChart, 250);
    lv_obj_set_height(ui_UsageChart, 120);
    lv_obj_set_x(ui_UsageChart, 15);
    lv_obj_set_y(ui_UsageChart, -70);
    lv_obj_set_align(ui_UsageChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_UsageChart, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_UsageChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 0, 2, true, 50);
    lv_chart_set_axis_tick(ui_UsageChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_UsageChart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 0, 2, true, 25);
    //设置栅线格数，点和线的大小
    lv_chart_set_div_line_count(ui_UsageChart, 10, 10);
    lv_chart_set_point_count(ui_UsageChart, 100);
    lv_obj_set_style_line_width(ui_UsageChart, 2, LV_PART_ITEMS);
    lv_obj_set_style_width(ui_UsageChart, 1, LV_PART_INDICATOR);

    // lv_chart_series_t * ui_UsageChart_series_1 = lv_chart_add_series(ui_UsageChart, lv_color_hex(0xF30303),
    //                                                                  LV_CHART_AXIS_PRIMARY_Y);
    ui_UsageChart_series_1 = lv_chart_add_series(ui_UsageChart, lv_color_hex(0xF30303),LV_CHART_AXIS_PRIMARY_Y);

    // static lv_coord_t ui_UsageChart_series_1_array[] = { 10, 20, 40, 80, 80, 40, 20, 10, 0, 90, 100 };
    // lv_chart_set_ext_y_array(ui_UsageChart, ui_UsageChart_series_1, ui_UsageChart_series_1_array);
    // lv_chart_series_t * ui_UsageChart_series_2 = lv_chart_add_series(ui_UsageChart, lv_color_hex(0x20C349),
    //                                                                  LV_CHART_AXIS_SECONDARY_Y);
    ui_UsageChart_series_2 = lv_chart_add_series(ui_UsageChart, lv_color_hex(0x20C349),LV_CHART_AXIS_PRIMARY_Y);
    // static lv_coord_t ui_UsageChart_series_2_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    // lv_chart_set_ext_y_array(ui_UsageChart, ui_UsageChart_series_2, ui_UsageChart_series_2_array);

    ui_CpuTempBar = lv_bar_create(ui_OtherUI);
    lv_bar_set_value(ui_CpuTempBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_CpuTempBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_CpuTempBar, 184);
    lv_obj_set_height(ui_CpuTempBar, 11);
    lv_obj_set_x(ui_CpuTempBar, 65);
    lv_obj_set_y(ui_CpuTempBar, 25);

    ui_NetUpLabel = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_NetUpLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetUpLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetUpLabel, 0);
    lv_obj_set_y(ui_NetUpLabel, 120);
    lv_obj_set_align(ui_NetUpLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetUpLabel, "Update");

    ui_NetDwLabel = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_NetDwLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetDwLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetDwLabel, 0);
    lv_obj_set_y(ui_NetDwLabel, 150);
    lv_obj_set_align(ui_NetDwLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetDwLabel, "Download");

    ui_CpuTitleLabel = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_CpuTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CpuTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_CpuTitleLabel, "CPU Model");
    lv_obj_set_style_text_color(ui_CpuTitleLabel, lv_color_hex(0xF30303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CpuTitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CpuTitleLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GpuTitleLabel = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_GpuTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GpuTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GpuTitleLabel, 0);
    lv_obj_set_y(ui_GpuTitleLabel, 40);
    lv_label_set_text(ui_GpuTitleLabel, "GPU Model");
    lv_obj_set_style_text_color(ui_GpuTitleLabel, lv_color_hex(0x20C349), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GpuTitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GpuTitleLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RamBar = lv_bar_create(ui_OtherUI);
    lv_bar_set_value(ui_RamBar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_RamBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_RamBar, 70);
    lv_obj_set_height(ui_RamBar, 75);
    lv_obj_set_x(ui_RamBar, 10);
    lv_obj_set_y(ui_RamBar, 235);
    lv_obj_set_style_radius(ui_RamBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RamBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_RamLabel = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_RamLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RamLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RamLabel, 27);
    lv_obj_set_y(ui_RamLabel, 310);
    lv_label_set_text(ui_RamLabel, "RAM");

    ui_GRamBar = lv_bar_create(ui_OtherUI);
    lv_bar_set_value(ui_GRamBar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_GRamBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_GRamBar, 70);
    lv_obj_set_height(ui_GRamBar, 75);
    lv_obj_set_x(ui_GRamBar, 170);
    lv_obj_set_y(ui_GRamBar, 235);
    lv_obj_set_style_radius(ui_GRamBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_GRamBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_GRamLabel = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_GRamLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GRamLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GRamLabel, 183);
    lv_obj_set_y(ui_GRamLabel, 310);
    lv_label_set_text(ui_GRamLabel, "GRAM");

    ui_GpuPowerLabel = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_GpuPowerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GpuPowerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GpuPowerLabel, 20);
    lv_obj_set_y(ui_GpuPowerLabel, 63);
    lv_label_set_text(ui_GpuPowerLabel, "20.3W");

    ui_CpuPowerLabel = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_CpuPowerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CpuPowerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CpuPowerLabel, 20);
    lv_obj_set_y(ui_CpuPowerLabel, 23);
    lv_label_set_text(ui_CpuPowerLabel, "17.6W");

    ui_CpuTempLabel = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_CpuTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CpuTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CpuTempLabel, 255);
    lv_obj_set_y(ui_CpuTempLabel, 23);
    lv_label_set_text(ui_CpuTempLabel, "46.7°");

    ui_GpuTempLabel = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_GpuTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GpuTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GpuTempLabel, 255);
    lv_obj_set_y(ui_GpuTempLabel, 63);
    lv_label_set_text(ui_GpuTempLabel, "45.2°");

    ui_GpuTempBar = lv_bar_create(ui_OtherUI);
    lv_bar_set_value(ui_GpuTempBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_GpuTempBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_GpuTempBar, 183);
    lv_obj_set_height(ui_GpuTempBar, 11);
    lv_obj_set_x(ui_GpuTempBar, 65);
    lv_obj_set_y(ui_GpuTempBar, 65);

    ui_RamUsedLabel = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_RamUsedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RamUsedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RamUsedLabel, 85);
    lv_obj_set_y(ui_RamUsedLabel, 296);
    lv_label_set_text(ui_RamUsedLabel, "14.4/28G");

    ui_RamUsageLabel = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_RamUsageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RamUsageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RamUsageLabel, 85);
    lv_obj_set_y(ui_RamUsageLabel, 275);
    lv_label_set_text(ui_RamUsageLabel, "40%");

    ui_GRamUsedLabel = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_GRamUsedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GRamUsedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GRamUsedLabel, 245);
    lv_obj_set_y(ui_GRamUsedLabel, 296);
    lv_label_set_text(ui_GRamUsedLabel, "2.3/8G");

    ui_GRamUsageLabel = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_GRamUsageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GRamUsageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GRamUsageLabel, 245);
    lv_obj_set_y(ui_GRamUsageLabel, 275);
    lv_label_set_text(ui_GRamUsageLabel, "32%");

    ui_DwSpeedLabel = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_DwSpeedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DwSpeedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DwSpeedLabel, 110);
    lv_obj_set_y(ui_DwSpeedLabel, 150);
    lv_obj_set_align(ui_DwSpeedLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DwSpeedLabel, "10.2kb/s");

    ui_UpSpeedLabel = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_UpSpeedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UpSpeedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UpSpeedLabel, 110);
    lv_obj_set_y(ui_UpSpeedLabel, 120);
    lv_obj_set_align(ui_UpSpeedLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UpSpeedLabel, "300kb/s");

    ui_NetTitleLabel = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_NetTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetTitleLabel, -100);
    lv_obj_set_y(ui_NetTitleLabel, 135);
    lv_obj_set_align(ui_NetTitleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetTitleLabel, "Internet");
    lv_obj_set_style_text_font(ui_NetTitleLabel, &font_harmony_sans_20, 0);

    ui_MonitorTime = lv_label_create(ui_OtherUI);
    lv_obj_set_width(ui_MonitorTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MonitorTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MonitorTime, 0);
    lv_obj_set_y(ui_MonitorTime, 190);
    lv_obj_set_align(ui_MonitorTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MonitorTime, "20:48");
    lv_obj_set_style_text_font(ui_MonitorTime, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
}
